<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [7]:

# Your code here
import numpy as np

def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting("Super Man")

greeting(name="Super Man")

greet=greeting(name='Super Man')
print(greet)

print(greeting(name='Super Man'))

def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
print(list_min)

Hello Super Man!
Hello Super Man!
1


### 1.2 Named functions that don’t return


# eg. Print or saving data to file.


### 1.3 Anonymous functions

In [11]:

# Your code here
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [12]:

# Your code here
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting()

'Hello no one!'

## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [14]:



# Your solution here
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'


Hello hi!


The if condition is not satisfied, thus you can think of it as being 'skipped'. The console will continue running downwards to output the return of the original function.


## Exercise 2 :  Calculator functions

In [20]:



# Your solution here
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x, y):
    return x*y
def divide(x,y):
    if y.any()==0:
        return None
    return x/y
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [22]:



# Your solution here
def max_info(list):
    array = np.array(list)
    return np.max(array), np.argmax(array)

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

print(max_info(numbers))



(83, 2)
