<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [2]:

# Your code here
#assert condition-to-check, message
x = 10
assert x >= 0, "x is becoming negative!"
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [6]:

# Your code here
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.22
The square of 22 is 484!


In [8]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.Yuan Zhe
Oh oh! I cannot square Yuan Zhe!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [9]:

# Your code here
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121
#funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional

121

### 2.2 Docstrings

In [10]:

# Your code here
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



# failed reference on puritans

### 2.3 Function are first class citizens

In [ ]:

# Your code here
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0

### 2.4 More unpacking

In [14]:

# Your code here
x, y, z = [1, 2, 3]
print(x, y, z)

x, y, z = np.array([1, 2, 3])
print(x, y, z)

x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 2 3
1 2 3
1 [2, 3, 4] 5
1 5


## Exercise 1 :  A better calculator I

In [17]:



# Your solution here
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x, y):
    return x*y
def divide(x,y):
    return x/y

assert y==0, "This is not divisible!"

x=np.array([36, 34, 44, 76, 27,1])
y=np.array([64, 66, 56, 24, 73,0])

print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))



AssertionError: This is not divisible!

## Exercise 2 :  A better calculator II

In [37]:



# Your solution here
x=[6, 34, 44, 76, 27,1]
y=[64, 66, 56, 24, 73,0]

def add(x,y):
    return np.array(x)+np.array(y)
def subtract(x,y):
    return np.array(x)-np.array(y)
def multiply(x, y):
    return np.array(x)*np.array(y)

def divide(x, y):
    try:
        for i in range(len(y)):
                1/y[i]
                    
    except:
        print("Error: Cannot divide by zero.")

    else:
        return np.array(x)/np.array(y)



print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))


[ 70 100 100 100 100   1]
[-58 -32 -12  52 -46   1]
[ 384 2244 2464 1824 1971    0]
Error: Cannot divide by zero.
None


# Cant solve why the except is being ignored.