# Problema Uno

This two star problem makes me want to cry

In [17]:
def first_reason(z, v = 20, a = 1.25):
    denominator = ((a**2)+(z**2))**(1/2)
    return v*(1-(z/denominator))
print(first_reason(z=13/3))
print(first_reason(z=13/2))
print(first_reason(z=52/3))

0.7835281763821067
0.35987106038705363
0.051804313077774555


This two star problem is also not fun

NB: Imaginary numbers are represented by j

In [30]:
def second_reason(a,b,c):
    discriminant = (b**2)-(4*a*c)
    return ((-b + (discriminant**(1/2))/(2*a)),\
           (-b - (discriminant**(1/2))/(2*a)))
second_reason(4,1,2)

((-1+0.6959705453537527j), (-1-0.6959705453537527j))

The inner mind of a life science student that actually cannot do math. Hopefully you derive some entertainment if you do read through this.

The idea for solving the problem first:
N side polygon will have its edges touch the sides of the circle N times. 
Unit diameter I will take it as 1. This means my radius is 0.5
Back to secondary school math, I can divide this shit up into isoceles triangles (damnnnn this is so cool) (ie. 3 sides wil have 3 isoceles)

Calculate angle
Apply sin rule to get sides
$A = B(sin(a)/sin(b))$

In [58]:
import numpy as np
unit_length = 0.5
def third_reason(n):
    global unit_length #this is not necessary but its just for me to check
    alpha = 2*(np.pi)/n
    beta = (np.pi-alpha)/2
    iso_length = unit_length*((np.sin(alpha)/np.sin(beta)))
    return iso_length*n
print(third_reason(1000))
print("Holy shit I can do secondary school math")

3.141587485879563
Holy shit I can do secondary school math


Abusing array and panda

In [87]:
import pandas as pd
data_set = []
for i in range(1, 100, 10): #Because I am lazy
    data_set.append([third_reason(i)])
df = pd.DataFrame(np.array(data_set),
                  index = [str(i) for i in range(1,100,10)],
                 columns = ['Perimeter'])
df

Perimeter
1   1.224647e-16
11  3.099058e+00
21  3.129888e+00
31  3.136218e+00
41  3.138519e+00
51  3.139606e+00
61  3.140204e+00
71  3.140568e+00
81  3.140805e+00
91  3.140969e+00

I could show you to infinity, but i think this is more than enough.

Damn back to physics?

I want a function that will tell me everytime height cross 0.25
Am I supposed to be big brain enough to care about whether the ball bounces back up?
Obviously not lmao

In [88]:
def fourth_reason(h,g):
    sequence = []
    i = h
    while i > 0:
        sequence.append(((h-i)*2/g)**(1/2))
        i -= 0.25
    return sequence
data_sadge = np.array(fourth_reason(10,9.8))
df_two = pd.DataFrame(data_sadge,
                      columns = ['Time'])
df_two

Time
0   0.000000
1   0.225877
2   0.319438
3   0.391230
4   0.451754
5   0.505076
6   0.553283
7   0.597614
8   0.638877
9   0.677631
10  0.714286
11  0.749149
12  0.782461
13  0.814411
14  0.845154
15  0.874818
16  0.903508
17  0.931315
18  0.958315
19  0.984575
20  1.010153
21  1.035098
22  1.059457
23  1.083268
24  1.106567
25  1.129385
26  1.151751
27  1.173691
28  1.195229
29  1.216385
30  1.237179
31  1.257630
32  1.277753
33  1.297564
34  1.317078
35  1.336306
36  1.355262
37  1.373956
38  1.392399
39  1.410601

Chess but *2?

Feeling sus and going with default print statements because it is 3am

In [110]:
board_1 = [([1] + list((i-i) for i in range(14)) + [1]) for j in range(16)]
board_1_array = np.array(board_1)
print("The mean is " + str(np.mean(board_1_array)) + " " + "\n"\
      "The standard deviation is " + str(np.std(board_1_array)) + " " + "\n"\
      "The shape is " + str(np.shape(board_1_array)) + " " + "\n"\
      "The size is " + str(len(board_1_array)))

The mean is 0.125 
The standard deviation is 0.33071891388307384 
The shape is (16, 16) 
The size is 16


In [122]:
board_2 = [list(0 if i%2 == 0 else 1 for i in range(16)) for i in range(16)]
board_2_array = np.array(board_2)
print("The mean is " + str(np.mean(board_2_array)) + " " + "\n"\
      "The standard deviation is " + str(np.std(board_2_array)) + " " + "\n"\
      "The shape is " + str(np.shape(board_2_array)) + " " + "\n"\
      "The size is " + str(len(board_2_array)))

The mean is 0.5 
The standard deviation is 0.5 
The shape is (16, 16) 
The size is 16


The np.arrange function gives me 6 because 100/5 = 20. I have assumed that the last 4 digits will be ommited and I will thus change it to 1,80

In [130]:
np.arange(1, 100, 5)
board_3 = [list(i if i%3==0 else -i for i in range(1, 81, 5)) for j in range(16)]
board_3_array = np.array(board_3)
print("The mean is " + str(np.mean(board_3_array)) + " " + "\n"\
      "The standard deviation is " + str(np.std(board_3_array)) + " " + "\n"\
      "The shape is " + str(np.shape(board_3_array)) + " " + "\n"\
      "The size is " + str(len(board_3_array)))

The mean is -16.0 
The standard deviation is 41.922547632509165 
The shape is (16, 16) 
The size is 16


# Problema Dos

In [149]:
A = np.arange(1, 13).reshape(3, 4)
A[1]

array([5, 6, 7, 8])

In [150]:
A[:, np.array([i%3==0 for i in range(1,5)])]

array([[ 3],
       [ 7],
       [11]])

In [153]:
A[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [154]:
A[:, np.array([i!=1 for i in range(1,5)])]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [155]:
A[:2, np.array([i!=1 for i in range(1,5)])]

array([[2, 3, 4],
       [6, 7, 8]])

In [157]:
A[:2, np.array([i!=1 and i !=4 for i in range(1,5)])]

array([[2, 3],
       [6, 7]])

In [160]:
A[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [161]:
A[::2, np.array([i==1 or i==2 for i in range(1,5)])]

array([[ 1,  2],
       [ 9, 10]])

In [162]:
A[::2, np.array([i==1 or i==3 for i in range(1,5)])]

array([[ 1,  3],
       [ 9, 11]])