<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [9]:

# Your code here
import math
import numpy as np

#Python Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#Numpy Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#Dictionary
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [10]:

# Your code here
print(py_real_names[0])
print(py_super_names[0])
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.
print(py_super_names[-1])   # Reverse indexing

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [15]:

# Your code here
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])
print(superhero_info.keys())
print(superhero_info.values())

Black Widow
dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


### 1.4 Higher dimensional lists

In [16]:

# Your code here
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [21]:

# Your code here
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
print(len(py_list_2d))
print(len(np_array_2d))
print(np_array_2d.shape) #Shape is not a function, but rather a property or attribute

10
10
(10, 2)


Array is unique to numpy

### 2.2 Arrays are fussy about type

In [25]:

# Your code here
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

These are all converted to strings

### 2.3 Adding a number

In [27]:

# Your code here
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
#py_list + 10        # Won't work!
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [30]:

# Your code here
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)
print(np_array_1 + np_array_2)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


### 2.5 Multiplying by a Number

In [5]:

# Your code here
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(py_list*2)
print(np_array*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


To convert type in list, use for loop

### 2.6 Squaring

In [4]:

# Your code here
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#py_list**2                      # Won't work!  
print(np_array**2)

[ 1  4  9 16 25]


### 2.7 Asking questions

In [14]:

# Your code here
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)     
print(py_list == 3)     # Works, but what IS the question?
#py_list > 3      # Won't work!
print(np_array == 3)  
print(np_array > 3)  

False
[False False  True False False]
[False False False  True  True]


# Question: What does the py_list == 3 check for?
Does it just check for the direct value, since the list is not 3, the answer will be false. 
On the contrary:

In [16]:
py_list = [1, 2, 3, 4, 5]
print (py_list == [1, 2, 3, 4, 5])

True


### 2.8 Mathematics

In [20]:

# Your code here
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(sum(py_list))     # sum() is a base Python function

print(max(py_list))     # max() is a base Python function

print(min(py_list))     # min() is a base Python function

#py_list.sum()   # Won't work!

print(np_array.sum())

print(np_array.mean())

print(np_array.max())

print(np_array.min())



15
5
1
15
3.0
5
1


## Exercise 1 :  Total recall?




# Your solution here
1. Two similarities between lists and arrays.
Both stores data
Both are mutable

2. Two differences between lists and arrays.
Lists are "fixed" eg. multiplying it by 2 merely multiplies the entire lists, whereas arrays multiplys individual data sets by 2.
Lists can store different types whereas arrays will convert all data sets to the same type.


## Exercise 2 :  Index me

In [21]:



# Your solution here
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                    # Prints 'a1'
print(py_list[2])                    # Prints 'c3'
print(py_list[4])                    # Prints 'e5'
print(py_list[6])                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'



a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [26]:



# Your solution here
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper() 
superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper() 
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper() 

print(superhero_info["Natasha Romanoff"])
print(superhero_info["Tony Stark"])
print(superhero_info["Stephen Strange"])

BLACK WIDOW
IRON MAN
DOCTOR STRANGE


In [33]:
#For the trolls
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
for i in superhero_info:
    superhero_info[i] = superhero_info[i].upper()

print(superhero_info["Natasha Romanoff"])
print(superhero_info["Tony Stark"])
print(superhero_info["Stephen Strange"])

BLACK WIDOW
IRON MAN
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [44]:



# Your solution here
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_array_numbers = np.array(numbers)

#Ask a question
np_array_count = np_array_numbers == 1

#Via sum
print(np_array_count.sum())

9
