<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:

# Your code here
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

|Syntax|	Result|		|Note|
|:-|:-|:-|:-|
|x[0]|	First element|	'a1'|	|
|x[-1]|	Last element	|'j10'	||
|x[0:3]	|Index 0 to 2|	['a1','b2','c3']	|Gives $3-0=3$ elements|
|x[1:6]|	Index 1 to 5|	['b2','c3','d4','e5','f6']|	Gives $6−1=5$ elements|
|x[1:6:2]|	Index 1 to 5 in steps of 2	|['b1','d4','f6']	|Gives every other of 6−1=5 elements|
|x[5:]|	Index 5 to the end|	['f6','g7','h8','i9','j10']|	Gives len(x)−5=5 elements|
|x[:5]	|Index 0 to 5	|['a1','b2','c3','d4','e5']|	Gives 5−0=5 elements|
|x[5:2:-1]	|Index 5 to 3 |(i.e. in reverse)	['f6','e5','d4']|	Gives 5−2=3 elements|
|x[::-1]|	Reverses the list|	['j10','i9','h8',...,'b2','a1']	|

### 1.2 Subsetting by masking (Arrays only)

In [6]:

# Your code here
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)
print(np_array[my_mask])
#OR
print(np_array[np_array > 3])

#These are for numpy
print(np_array[~(np_array > 3)])                        # '~' means 'NOT'
print(np_array[(np_array > 3) & (np_array < 8)])         # '&' means 'AND'
print(np_array[(np_array < 3) | (np_array > 8)])         # '|' means 'OR'




[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]
[1 2 3]
[4 5 6 7]
[ 1  2  9 10]


### 1.3 Indexing & Slicing 2D Lists

In [12]:

# Your code here
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
print(py_list_2d[3])        # What is at position 4 (index 3)?
print(py_list_2d[3][0])     # FIRST element at position 4 (index 3)
print(py_list_2d[:3])
print(py_list_2d[:3][0]) #First of the list from py_list_2d[:3]
print(py_list_2d[3:6][0]) #First of the list from py_list_2d[3:6]

[4, 'D']
4
[[1, 'A'], [2, 'B'], [3, 'C']]
[1, 'A']
[4, 'D']


### 1.4 Indexing & Slicing 2D Arrays

In [18]:

# Your code here
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])
print(np_array_2d[3])       # What is at position 4 (index 3)?
print(np_array_2d[3, 0])    # FIRST element at position 4 (index 3)

#Notice how the syntax for arrays uses just a single pair of square brackets ([ ]).

print(np_array_2d[:3])
print(np_array_2d[:3, 0]) #On the contrary, this gives you the FIRST of EACH SET
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

['4' 'D']
4
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]
['1' '2' '3']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


### 1.5 Growing lists

In [23]:

# Your code here
x=[1]*10
print(x)               # I am lazy to type print()
                # Let Jupyter do the hard work.

x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
print(x)

#OR

x=[1]
x+= [2]
x+= [3]
x+= [4]
print(x)

#Pre-pending
x=[1]
x= [2, 3, 4] + x
print(x)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 2, 3, 4]
[1, 2, 3, 4]
[2, 3, 4, 1]


## 2 Some loose ends

### 2.1 Tuples

In [24]:

# Your code here
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

# The following will NOT work
#a[0]=-1
#a[0] += [10]

1


### 2.2 Be VERY careful when copying

In [ ]:

# Your code here
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

x=[1, 2, 3]
y=x.copy()
z=x.copy()

Lists are mutable, so doing y=x binds them to the same object, modifying one modifies the other.

## Exercise 1 :  Total recall?




# Your solution here
|Term	|Brief description|
|:-|:-:|
|Subsetting	|Selecting element(s)|
|Indexing	|Selecting elements|
|Slicing	|Selects specific elements that suit a condition|
|Masking	|Similar to slicing|



## Exercise 2 :  Show me the ‘odd’ letters

In [53]:



# Your solution here
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

#Subsetting the first elements
np_array_subset = np_array_2d.copy()
np_array_subset_filtered = np_array_subset[:, 0]
np_array_subset_int = np_array_subset_filtered.astype(int)
np_array_subset_calc = np_array_subset_int%2
#I now know that the positions are 1,2,5,6,10
np_array_ans = np_array_2d[0, 1], np_array_2d[1, 1], np_array_2d[4, 1], np_array_2d[5, 1], np_array_2d[9, 1]
print(np_array_ans)

('A', 'C', 'E', 'G', 'I')


In [113]:
#Testing
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
#Convert to list
list_2d = np_array_2d.tolist()
new_list=[]
for i in list_2d:
    i[0]=int(i[0])
    if i[0]%2 == 1:
        new_list.append(i[1])    
print(new_list)

['A', 'C', 'E', 'G', 'I']
